Reorg bug fix
frozeman/vanguard-consensus-engine pull request #73
Opened 2021-11-04 10:56 UTC by atif-konasl

**What type of PR is this?**
> Bug fix

**What does this PR do? Why is it needed?**
This PR will fix bug of current l15 reorg.

**Which issues(s) does this PR fix?**

Fixes #

**Other notes for review**

2021-11-04 11:32 UTC, blazejkrzak requested changes
we miss tests

2021-11-04 11:46 UTC, atif-konasl commented
> we miss tests

Yeah you right. It's not a massive change so we can test for these simple getter and setter method `setLatestSentEpoch` and `getLatestSentEpoch` later.

2021-11-04 13:25 UTC, blazejkrzak commented
> > we miss tests
> 
> Yeah you right. It's not a massive change so we can test for these simple getter and setter method `setLatestSentEpoch` and `getLatestSentEpoch` later.

what does block us to write meaningful tests now?

2021-11-04 13:33 UTC, rryter commented
I agree, let's add the tests now.

2021-11-04 13:56 UTC, blazejkrzak commented on proto/eth/v1alpha1/beacon_chain.proto
> +
redundant newline

2021-11-04 15:41 UTC, atif-konasl commented
> > > we miss tests
> > 
> > 
> > Yeah you right. It's not a massive change so we can test for these simple getter and setter method `setLatestSentEpoch` and `getLatestSentEpoch` later.
> 
> what does block us to write meaningful tests now?

Time is blocking us. I am really bz with testing clients in our vms. Could you provide some test cases?

2021-11-04 15:41 UTC, atif-konasl commented on proto/eth/v1alpha1/beacon_chain.proto
> +
Removing

2021-11-04 16:45 UTC, mxmar commented on proto/eth/v1alpha1/beacon_chain.proto
> +
After remove please close/solve this conversation :)

2021-11-05 10:46 UTC, mxmar requested changes
Implementation in overall look ok to me but I agree that we should provide component test on top of it to avoid next network stall and confirm fix. Anyway I think we can build/release binary of it and provide to community who faced network stall.

2021-11-05 10:47 UTC, mxmar commented
I'm working on `vanguard` side trying to provide proper test scenario on top of this PR changes: https://github.com/lukso-network/vanguard-consensus-engine/pull/74

2021-11-09 15:59 UTC, merged